# Generated by Django 4.2.7 on 2023-12-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_districts_remove_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shift',
        ),
    ]
