# Generated by Django 4.2.7 on 2023-12-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='detention_show',
        ),
    ]
