# Generated by Django 4.2.7 on 2023-12-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_detention_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
