from django.db import models
from detainees.models import Detainee, Photos
from districts.models import District
from users.models import User

# Create your models here.
# class Process(models.Model):
#     name = models.CharField(max_length=255)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

class Records(models.Model):
    folio_afi = models.CharField(max_length=255, null=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=False)
    detainee = models.ForeignKey(Detainee, on_delete=models.CASCADE, null=False)
    entry_date = models.DateTimeField()
    qualification_release_date = models.DateTimeField(null=True)
    official_release_date = models.DateTimeField(null=True)
    process = models.CharField(max_length=255, null=True)
    fundament = models.IntegerField(null=True)
    release_type = models.CharField(max_length=255, null=True)
    release_reason = models.CharField(max_length=255, null=True)
    release_important_cell_note = models.CharField(max_length=255, null=True)
    notes = models.CharField(max_length=255, null=True)
    detainee_photo = models.ForeignKey(Photos, on_delete=models.CASCADE, null=True)
    # place_type = models.CharField(max_length=255, null=True)
    # clasification_detention_place = models.CharField(max_length=255, null=True)
    # country = models.CharField(max_length=255, null=True)
    sanction = models.CharField(max_length=255, null=True)
    # municipality = models.CharField(max_length=255, null=True)
    # locality = models.CharField(max_length=255, null=True)
    # colony = models.CharField(max_length=255, null=True)
    # street = models.CharField(max_length=255, null=True)
    # interior_number = models.CharField(max_length=255, null=True)
    # exterior_number = models.CharField(max_length=255, null=True)
    # corner_street = models.CharField(max_length=255, null=True)
    # reason = models.CharField(max_length=255, null=True)
    # unity_number = models.CharField(max_length=255, null=True)
    # sector = models.CharField(max_length=255, null=True)
    iph_path = models.CharField(max_length=255, null=True)
    is_active = models.BooleanField(default=True)
    has_been_released = models.BooleanField(null=True, default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
class Cells(models.Model):
    record = models.ForeignKey(Records, on_delete=models.CASCADE, null=False)
    cell = models.CharField(max_length=255, null=True)
    cell_notes = models.CharField(max_length=255, null=True)
    registered_by = models.CharField(max_length=255, null=True)
    assignment_folio = models.CharField(max_length=255, null=True)
    created_by = models.CharField(max_length=60, null=True)
    registered_belongings = models.BooleanField(null=True, default=False)
    registered_calls = models.BooleanField(null=True, default=False)
    total_belongings = models.IntegerField(null=True)
    total_calls = models.IntegerField(null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Events(models.Model):
    record = models.ForeignKey(Records, on_delete=models.CASCADE, null=False)
    qualifies = models.BooleanField(null=True)
    minimum_salaries = models.IntegerField(null=True)
    qualified_hours = models.IntegerField(null=True)
    aggravating_factors = models.IntegerField(null=True)
    adjustment = models.CharField(max_length=100, null=True)
    total_payable = models.FloatField(null=True)
    basis = models.CharField(max_length=255, null=True)
    event_datetime = models.DateTimeField()
    detention_folio = models.CharField(max_length=100, null=True)
    discriminator = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    subtype = models.CharField(max_length=100, null=True)
    violence = models.CharField(max_length=100, null=True)
    ambient = models.CharField(max_length=100, null=True)
    movil = models.CharField(max_length=100, null=True)
    modus_operandi = models.CharField(max_length=100, null=True)
    event_description = models.CharField(max_length=100, null=True)
    detention_datetime = models.DateTimeField()
    detention_type = models.CharField(max_length=100)
    reason = models.CharField(max_length=255, null=True)
    arrested_by = models.CharField(max_length=255, null=True)
    place = models.CharField(max_length=255, null=True)
    unit = models.CharField(max_length=255, null=True)
    sector = models.CharField(max_length=255, null=True)
    clasification = models.CharField(max_length=255, null=True)
    locality = models.CharField(max_length=255, null=True)
    municipality = models.CharField(max_length=255, null=True)
    country = models.CharField(max_length=255, null=True)
    street = models.CharField(max_length=255, null=True)
    exterior_number = models.CharField(max_length=255, null=True)
    interior_number = models.CharField(max_length=255, null=True)
    colony = models.CharField(max_length=255, null=True)
    cross_street = models.CharField(max_length=255, null=True)
    is_active = models.BooleanField(default=True)
    created_by = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
class Offended(models.Model):
    event = models.ForeignKey(Events, on_delete=models.CASCADE, null=False)
    name = models.CharField(max_length=255)
    fathers_name = models.CharField(max_length=255)
    mothers_name = models.CharField(max_length=255, null=True)
    relationship = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class RecordsPoliceAgents(models.Model):
    employee_number = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    record = models.ForeignKey(Records, on_delete=models.CASCADE, null=False)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

# class CellNotes(models.Model):
#     record = models.ForeignKey(Records, on_delete=models.CASCADE, null=False)
#     note = models.CharField(max_length=255)
#     is_active = models.BooleanField(default=True)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

class Belongings(models.Model):
    # record = models.ForeignKey(Records, on_delete=models.CASCADE, null=False)
    cell = models.ForeignKey(Cells, on_delete=models.CASCADE, null=False)
    registration_datetime = models.DateTimeField(null=True)
    document_mexican_passport = models.BooleanField(null=True, default=False)
    document_american_passport = models.BooleanField(null=True, default=False)
    document_residence = models.BooleanField(null=True, default=False)
    document_ine = models.BooleanField(null=True, default=False)
    document_other = models.BooleanField(null=True, default=False)
    document_notes = models.CharField(null=True, max_length=255)
    jewelry_earrings = models.BooleanField(null=True, default=False)
    jewelry_ring = models.BooleanField(null=True, default=False)
    jewelry_chain = models.BooleanField(null=True, default=False)
    jewelry_bracelet = models.BooleanField(null=True, default=False)
    jewelry_clock = models.BooleanField(null=True, default=False)
    jewelry_other = models.BooleanField(null=True, default=False)
    jewelry_notes = models.CharField(null=True, max_length=255)
    devices_keys = models.BooleanField(null=True, default=False)
    devices_cables = models.BooleanField(null=True, default=False)
    devices_laptop = models.BooleanField(null=True, default=False)
    devices_cellphone = models.BooleanField(null=True, default=False)
    devices_aux = models.BooleanField(null=True, default=False)
    devices_charger = models.BooleanField(null=True, default=False)
    devices_tablet = models.BooleanField(null=True, default=False)
    devices_usb = models.BooleanField(null=True, default=False)
    devices_computer_equipment = models.BooleanField(null=True, default=False)
    devices_notes = models.CharField(null=True, max_length=255)
    accesories_cap = models.BooleanField(null=True, default=False)
    accesories_ribbons = models.BooleanField(null=True, default=False)
    accesories_shoes = models.BooleanField(null=True, default=False)
    accesories_backpack = models.BooleanField(null=True, default=False)
    accesories_sunglasses = models.BooleanField(null=True, default=False)
    accesories_cigarettes = models.BooleanField(null=True, default=False)
    accesories_belt = models.BooleanField(null=True, default=False)
    accesories_handbag = models.BooleanField(null=True, default=False)
    accesories_other = models.BooleanField(null=True)
    accesories_notes = models.CharField(null=True, max_length=255)
    money_mexican_pesos = models.IntegerField(null=True)
    money_american_dollars = models.IntegerField(null=True, default=False)
    bank_cards = models.CharField(null=True, max_length=255)
    delivered = models.BooleanField(null=True, default=False)
    delivered_to_another = models.BooleanField(null=True, default=False)
    delivery_notes = models.CharField(null=True, max_length=255)
    delivery_relationship = models.CharField(null=True, max_length=255)
    delivery_datetime = models.DateTimeField(null=True)
    delivered_to = models.CharField(max_length=255, null=True, default=False)
    written_to = models.CharField(max_length=255, null=True, default=False)
    remission = models.CharField(max_length=255, null=True, default=False)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class CallsRegistry(models.Model):
    cell = models.ForeignKey(Cells, on_delete=models.CASCADE, null=False)
    call_datetime = models.DateTimeField(null=True)
    had_response = models.BooleanField(default=False, null=True)
    accepted = models.BooleanField(default=False, null=True)
    user = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=100, null=True)
    phone_number = models.CharField(max_length=255, null=True)
    detainee_relationship = models.CharField(max_length=255, null=True)
    is_active = models.BooleanField(default=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class MedicalInformation(models.Model):
    record = models.ForeignKey(Records, on_delete=models.CASCADE, null=False)
    folio = models.CharField(max_length=40, null=True)
    weight = models.CharField(max_length=255)
    height = models.CharField(max_length=255)
    intoxication = models.CharField(max_length=255)
    mental = models.CharField(max_length=255)
    general_condition = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    medic_name = models.CharField(max_length=255, null=True)
    medical_cedula = models.CharField(max_length=255, null=True)
    medical_date_time = models.DateTimeField(null=True)
    pathologies = models.CharField(max_length=255)
    medical_t = models.CharField(max_length=255)
    medical_fc = models.CharField(max_length=255)
    medical_fr = models.CharField(max_length=255)
    medical_ta = models.CharField(max_length=255)
    saturation = models.CharField(max_length=255)
    diagnostic = models.CharField(max_length=255)
    blood_type = models.CharField(max_length=255)
    created_by = models.CharField(max_length=255, null=True)
    rh_factor = models.CharField(max_length=255)
    has_lesions = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    #medical_t
    #medical_fc
    #medical_fr
    #medical_ta
    #medical_cedula from medic model
    #detainee nombre completo
    #gender sexo del detenido
    #age edad del detenido


class LesionsPhotos(models.Model):
    image_path = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Lesions(models.Model):
    medical_information = models.ForeignKey(MedicalInformation, on_delete=models.CASCADE, null=False)
    location = models.CharField(max_length=255)
    discriminator = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True)
    notes = models.CharField(max_length=255, null=True)
    image_path = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class OtherRecords(models.Model):
    #record = models.ForeignKey(Records, on_delete=models.CASCADE, null=True)    
    district= models.CharField(max_length=255, null=True)
    reason = models.CharField(max_length=255, null=True)
    other_record_folio = models.CharField(max_length=255, null=True)
    date = models.DateTimeField(default=True, null=True)
    detention_type = models.CharField(max_length=255, null=True)
    place = models.CharField(max_length=255, null=True)
    holder_name = models.CharField(max_length=255, null=True)
    vehicle_type = models.CharField(max_length=255, null=True)
    brand = models.CharField(max_length=255, null=True)
    created_by = models.CharField(max_length=255, null=True)
    line = models.CharField(max_length=255, null=True)
    discriminator = models.CharField(max_length=255, null=True)
    type = models.CharField(max_length=255, null=True)
    subtype = models.CharField(max_length=255, null=True)
    description = models.CharField(max_length=255, null=True)
    quantity = models.CharField(max_length=255, null=True)
    general_condition = models.CharField(max_length=255, null=True)
    model = models.CharField(max_length=255, null=True)
    color = models.CharField(max_length=255, null=True)
    plates = models.CharField(max_length=255, null=True)
    serial_number = models.CharField(max_length=255, null=True)
    stamp_number = models.CharField(max_length=255, null=True)
    emission_number = models.CharField(max_length=255, null=True)
    association_expeditor = models.CharField(max_length=255, null=True)
    comments = models.CharField(max_length=255, null=True)
    image_path = models.CharField(max_length=255, null=True)
    is_active = models.BooleanField(default=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class OtherRecordsDetainees(models.Model):
    other_record = models.ForeignKey(OtherRecords, on_delete=models.CASCADE, null=True)
    detainee = models.ForeignKey(Detainee, on_delete=models.CASCADE, null=True)
    relation_folio = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, null=True)
    fathers_name = models.CharField(max_length=255, null=True)
    mothers_name = models.CharField(max_length=255, null=True)
    related_to_detention = models.CharField(max_length=255, null=True)
    detention_entry_date = models.DateTimeField(null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



# class Objects(models.Model):
#     record = models.ForeignKey(Records, on_delete=models.CASCADE, null=True)
#     detainee = models.ForeignKey(Detainee, on_delete=models.CASCADE, null=True)
#     reason = models.CharField(max_length=255)
#     discriminator = models.CharField(max_length=255)
#     subtype = models.CharField(max_length=255)
#     quantity = models.CharField(max_length=255)
#     general_condition = models.CharField(max_length=255)
#     description = models.CharField(max_length=255)
#     is_active = models.BooleanField(default=True)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)


class Faults(models.Model):
    event = models.ForeignKey(Events, on_delete=models.CASCADE, null=False)
    type = models.CharField(max_length=255)
    subtype = models.CharField(max_length=255)
    discriminator = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Actions(models.Model):
    is_active = models.BooleanField(default=True)
    #is_group = models.BooleanField(default=False)
    record = models.ForeignKey(Records, on_delete=models.CASCADE, null=False)
    #user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    user = models.CharField(max_length=255, null=True)
        
    medic_name = models.CharField(max_length=255, null=True)
    medical_cedula = models.CharField(max_length=255, null=True)
    medical_date_time = models.CharField(max_length=255, null=True)
    discriminator = models.CharField(max_length=255, null=True)
    action_folio = models.CharField(max_length=255, null=True)
    office_number = models.CharField(max_length=255, null=True)
    detainee = models.CharField(max_length=255, null=True)
    age = models.CharField(max_length=255, null=True)
    nationality = models.CharField(max_length=255, null=True)
    address = models.CharField(max_length=255, null=True)
    relative = models.CharField(max_length=255, null=True)
    relative_age = models.CharField(max_length=255, null=True)
    identification = models.CharField(max_length=255, null=True)
    id_number = models.CharField(max_length=255, null=True)
    affinity = models.CharField(max_length=255, null=True)
    medical_certificate = models.CharField(max_length=255, null=True)
    description = models.CharField(max_length=255, null=True)
    district_name = models.CharField(max_length=255, null=True)
    # district = models.ForeignKey(District, on_delete=models.CASCADE, null=False)
    date = models.CharField(max_length=255, null=True)
    hour = models.CharField(max_length=255, null=True)
    article = models.CharField(max_length=255, null=True)
    fraction = models.CharField(max_length=255, null=True)
    number = models.CharField(max_length=255, null=True)
    infraction_number = models.CharField(max_length=255, null=True)
    unit = models.CharField(max_length=255,null=True)
    agent1 = models.CharField(max_length=255, null=True)
    agent2 = models.CharField(max_length=255, null=True)
    action_date = models.DateTimeField(null=True)
    devices_laptop= models.BooleanField(null=True,default=False)
    devices_charger = models.BooleanField(null=True,default=False)
    accesories_cap = models.BooleanField(null=True, default=False)
    money_mexican_pesos = models.CharField(max_length=255, null=True)
    money_american_dollars = models.CharField(max_length=255, null=True)
    remission = models.CharField(max_length=255, null=True)
    subject_to = models.CharField(max_length=255, null=True)
    subject = models.CharField(max_length=255, null=True)
    written_to = models.CharField(max_length=255, null=True)
    crime = models.CharField(max_length=255, null=True)
    victim = models.CharField(max_length=255, null=True)
    other = models.CharField(max_length=255, null=True)
    agent_name = models.CharField(max_length=255, null=True)
    agent_job = models.CharField(max_length=255, null=True)
    agent_number = models.CharField(max_length=255, null=True)
    agent_unit = models.CharField(max_length=255, null=True)
    has_ministerio_publico= models.BooleanField(null=True,default=False)
    has_iph= models.BooleanField(null=True,default=False)
    has_chain_custody= models.BooleanField(null=True,default=False)
    has_medical_certificate= models.BooleanField(null=True,default=False)
    has_car_inventory= models.BooleanField(null=True,default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ActionNotes(models.Model):
    is_active = models.BooleanField(default=True)
    action = models.ForeignKey(Actions, on_delete=models.CASCADE, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class ParticularSigns(models.Model):
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)