# Generated by Django 4.2.7 on 2023-12-11 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('nicknames', models.CharField(max_length=500, null=True)),
                ('fake_names', models.CharField(max_length=500, null=True)),
                ('marital_status', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('sexual_preferences', models.CharField(max_length=255, null=True)),
                ('ethnicity', models.CharField(max_length=255, null=True)),
                ('schooling', models.CharField(max_length=255, null=True)),
                ('occupation', models.CharField(max_length=255, null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorsRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255, null=True)),
                ('visit_date', models.CharField(max_length=255)),
                ('detainee_relationship', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.detainee')),
            ],
        ),
        migrations.CreateModel(
            name='TattooClasifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasification', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.detainee')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.detainee')),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.detainee')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.detainee')),
            ],
        ),
        migrations.CreateModel(
            name='FakeNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.detainee')),
            ],
        ),
        migrations.CreateModel(
            name='DistinguishingMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tattoo_clasification', models.CharField(default=True, max_length=255)),
                ('tattoo_description', models.CharField(default=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.detainee')),
                ('tattoo_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.tattooclasifications')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriminator', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=255, null=True)),
                ('exterior_number', models.CharField(max_length=255, null=True)),
                ('interior_number', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('colony', models.CharField(max_length=255, null=True)),
                ('locality', models.CharField(max_length=255, null=True)),
                ('municipality', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detainees.detainee')),
            ],
        ),
    ]
