# Generated by Django 4.2.7 on 2023-12-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='action_date',
            field=models.DateTimeField(),
        ),
    ]
