# Generated by Django 4.2.7 on 2023-12-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_actions_action_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='folio',
            new_name='action_folio',
        ),
    ]
