# Generated by Django 4.2.7 on 2023-12-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_folio_actions_action_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='accesories_cap',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='devices_charger',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='devices_laptop',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='has_car_inventory',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='has_chain_custody',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='has_iph',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='has_medical_certificate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
