# Generated by Django 4.2.7 on 2023-12-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_actions_accesories_cap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='has_ministerio_publico',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
