# Generated by Django 4.2.7 on 2023-12-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_actions_has_ministerio_publico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherrecords',
            old_name='asociation_expeditor',
            new_name='association_expeditor',
        ),
    ]
