# Generated by Django 4.2.7 on 2023-12-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_rename_asociation_expeditor_otherrecords_association_expeditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecords',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
