# Generated by Django 4.2.7 on 2023-12-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_otherrecords_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='qualifies',
            field=models.BooleanField(null=True),
        ),
    ]
