# Generated by Django 4.2.7 on 2023-12-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_events_qualifies'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actions',
            name='subject_to',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
