# Generated by Django 4.2.7 on 2023-12-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_events_qualifies'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='has_been_released',
            field=models.BooleanField(default=True),
        ),
    ]
