# Generated by Django 4.2.7 on 2023-12-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_records_has_been_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='has_been_released',
            field=models.BooleanField(null=True),
        ),
    ]
