# Generated by Django 4.2.7 on 2023-12-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_records_has_been_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='adjustment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='ambient',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='detention_folio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='detention_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='discriminator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='modus_operandi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='movil',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='subtype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='violence',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
