# Generated by Django 4.2.7 on 2023-12-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_actions_subject_actions_subject_to'),
        ('records', '0012_alter_events_adjustment_alter_events_ambient_and_more'),
    ]

    operations = [
    ]
