# Generated by Django 4.2.7 on 2023-12-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_merge_20231213_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherrecords',
            name='detainee',
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='has_been_released',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
