# Generated by Django 4.2.7 on 2023-12-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_otherrecords_detainee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='release_date',
            new_name='official_release_date',
        ),
        migrations.AddField(
            model_name='records',
            name='qualification_release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
