# Generated by Django 4.2.7 on 2023-12-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_otherrecords_detainee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecords',
            name='association_expeditor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='discriminator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='general_condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='holder_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='line',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='other_record_folio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='plates',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='serial_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='stamp_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='subtype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecords',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
