# Generated by Django 4.2.7 on 2023-12-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_otherrecords_association_expeditor_and_more'),
        ('records', '0015_rename_release_date_records_official_release_date_and_more'),
    ]

    operations = [
    ]
