# Generated by Django 4.2.7 on 2023-12-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_merge_20231212_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherrecords',
            name='record',
        ),
        migrations.AddField(
            model_name='otherrecords',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otherrecords',
            name='emission_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otherrecords',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otherrecords',
            name='vehicle_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
