# Generated by Django 4.2.7 on 2023-12-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_remove_otherrecords_record_otherrecords_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsregistry',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='callsregistry',
            name='had_response',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
