# Generated by Django 4.2.7 on 2023-12-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_alter_callsregistry_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsregistry',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='callsregistry',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
