# Generated by Django 4.2.7 on 2023-12-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_alter_callsregistry_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cells',
            name='created_by',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
