# Generated by Django 4.2.7 on 2023-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_alter_callsregistry_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherrecordsdetainees',
            name='fathers_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecordsdetainees',
            name='mothers_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecordsdetainees',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecordsdetainees',
            name='related_to_detention',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherrecordsdetainees',
            name='relation_folio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
