# Generated by Django 4.2.7 on 2023-12-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_alter_otherrecordsdetainees_fathers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongings',
            name='delivered_to',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='belongings',
            name='delivery_notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
