# Generated by Django 4.2.7 on 2023-12-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_cells_created_by'),
        ('records', '0021_alter_belongings_delivered_to_and_more'),
    ]

    operations = [
    ]
