# Generated by Django 4.2.7 on 2023-12-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_merge_20231213_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrecordsdetainees',
            name='detention_entry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
