# Generated by Django 4.2.7 on 2023-12-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_otherrecordsdetainees_detention_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
