# Generated by Django 4.2.7 on 2023-12-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_events_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinformation',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
