# Generated by Django 4.2.7 on 2023-12-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_medicalinformation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrecords',
            name='detention_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
